# Création de vecteurs et matrices avec la classe ndarray

## Import de la librairie Numpy


In [12]:
import numpy as np

# Création d'arrays

## 1. Vecteur


In [14]:
A = np.array([1,2,3])
print(A)
type(A)

[1 2 3]


numpy.ndarray

## 2. Matrice


In [16]:
B = np.array([[1,2,3],[4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


In [18]:
C = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 3. Les attributs les plus utiles des objets arrays

### L'attribut shape

In [20]:
B.shape
C.shape
type(C.shape)

tuple

### L'attribut size


In [24]:
B.size

6

### L'attribut ndim


In [28]:
A.ndim

1

In [30]:
C.ndim

2

## 4. Les constructeurs alternatifs de ndarray


In [34]:
Z = np.zeros((2,3))
print(Z)

O = np.ones((3,5))
print(O)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
F = np.full((2,4), 5)
print(F)

[[5 5 5 5]
 [5 5 5 5]]


In [38]:
L = np.linspace(-5,5,10)
print(L)
L.size

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


10

In [44]:
M = np.arange(-5,6,2)
print(M)
M.size

[-5 -3 -1  1  3  5]


6