In [1]:
import numpy as np

## 1. Addition et soustraction

In [3]:
A = np.array([[-2,-3,0], [1,2,3]])
print(A)

[[-2 -3  0]
 [ 1  2  3]]


In [10]:
n_lin = A.shape[0]
n_col = A.shape[1]

In [8]:
B = np.ones((n_lin, n_col))
print(B)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
C = A + B
print(C)

[[-1. -2.  1.]
 [ 2.  3.  4.]]


## 2. Multiplication d'une matrice par un scalaire

In [15]:
coeff = 0.1
D = np.random.randint(-10,10,size=(3,3))
print(D)

[[-10   0  -4]
 [ -3  -7 -10]
 [ -1   3   3]]


In [17]:
E = coeff*D
print(E)

[[-1.   0.  -0.4]
 [-0.3 -0.7 -1. ]
 [-0.1  0.3  0.3]]


## 3. Produit terme à terme entre deux matrices


In [20]:
F = np.array([[1,2,3],[4,5,6]])
G = np.array([[1,2,3],[4,5,6]])
H = F*G
print(F)
print()
print(G)
print()
print(H)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]

[[ 1  4  9]
 [16 25 36]]


## 4. Produit matriciel


In [23]:
I = np.random.randint(-2,20,size=(5,3))
J = np.random.randint(-10,0,size=(3,4))

In [25]:
K = np.dot(I,J)
print(K)

[[ -61 -196 -178 -171]
 [-152 -218 -243  -93]
 [-159 -187 -223  -47]
 [ -37  -98 -153  -56]
 [-197 -194 -190  -33]]


In [27]:
K.shape

(5, 4)