In [2]:
import  numpy as np

## Indexing


In [4]:
A = np.array([1,2,3,4])
for i in range(len(A)):
    print(A[i])

1
2
3
4


In [6]:
B = np.array([[1,2,3],[4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


In [8]:
B[0,2]
B[0,-1]

3

## Slicing 

In [11]:
D = np.random.randint(-100,100,size=(4,4))
print(D)

[[ -7 -14 -29 -41]
 [-75 -98  42 -10]
 [  4   3  93  54]
 [-61 -71 -92  -8]]


In [13]:
E = D[:,-1]
print(E)

[-41 -10  54  -8]


In [15]:
F = D[1:3,:]
print(F)

[[-75 -98  42 -10]
 [  4   3  93  54]]


In [17]:
G = D[1:3,1:3]
print(G)

[[-98  42]
 [  3  93]]


In [19]:
H = D[:,0:3:2]
print(H)

[[ -7 -29]
 [-75  42]
 [  4  93]
 [-61 -92]]


## Boolean indexing


In [ ]:
I = np.random.randn(2,3)
print(I)